
export {default as Header} from './Header'
export {default as Introduction} from './Introduction' 
export {default as Rules} from './Rules' 
export {default as Statistics} from './Statistics'
export {default as FAQ} from './FAQ'
export {default as Dedication} from './Dedication'
export {default as Footer} from './Footer'
export {default as Benefits} from './Benefits'
export {default as Contact} from './Contact'
export {default as StatisticsCard} from './common/StatisticsCard'